service: react-air-server
provider:
  name: aws
  runtime: nodejs18.x
functions:
  server:
    handler: lambda.server
    events:
      - http:
          path: server
          method: get
          cors: true